# Site settings
title: 博客 - 商业、设计、编程和运营 - 但江
description: > # this means to ignore newlines until "baseurl:"
  来自于但江的思考，关注商业、设计、编程和运营
permalink: pretty
studio: "http://danthought.com"
wuhoo: "http://wuhoo.co/zh/"

# Build settings
markdown: kramdown

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
