# Site settings
title: 博客 - 商业、设计、编程和客服 - Dan Thought Studio
description: > # this means to ignore newlines until "baseurl:"
  来自于 Dan Thought Studio 的思考，关注商业、设计、编程和客服，每周更新
permalink: pretty
url: "http://blog.danthought.com" # the base hostname & protocol for your site
home: "http://danthought.com"

# Build settings
markdown: kramdown

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
